apiVersion: v1
entries:
  hub-agent:
  - apiVersion: v2
    appVersion: v0.99.0
    created: "2026-09-02T20:53:37.812565044Z"
    description: A Helm chart for hub agent
    digest: cc318dc5e75b0f2c01127bf847144b696b5631d8e8dbec4303b1cd3ef98fae23
    name: hub-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/hub-agent-0.99.0.tgz
    version: 0.99.0
  - apiVersion: v2
    appVersion: v0.98.0
    created: "2026-09-02T20:50:28.731988263Z"
    description: A Helm chart for hub agent
    digest: 24ceccc30cf16f92255b7075eeee8fa9111676d605adda721126b3a4a414c3c0
    name: hub-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/hub-agent-0.98.0.tgz
    version: 0.98.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.99.0
    created: "2026-09-02T20:53:37.813105903Z"
    description: Helm chart for member agent.
    digest: 0d1edc52ca0427beeb67756d64302833cf57d572c769010266301f8e0a32a552
    name: member-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/member-agent-0.99.0.tgz
    version: 0.99.0
  - apiVersion: v2
    appVersion: v0.98.0
    created: "2026-09-02T20:50:28.732561046Z"
    description: Helm chart for member agent.
    digest: 526cd7720cec8bcee7469ff570557fdbf1e62119bf7e5eeec3adfdf711d793e0
    name: member-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/member-agent-0.98.0.tgz
    version: 0.98.0
generated: "2026-09-02T20:53:37.806089304Z"
