apiVersion: v1
entries:
  hub-agent:
  - apiVersion: v2
    appVersion: v0.99.0
    created: "2026-09-02T20:53:37.812565044Z"
    description: A Helm chart for hub agent
    digest: cc318dc5e75b0f2c01127bf847144b696b5631d8e8dbec4303b1cd3ef98fae23
    name: hub-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/hub-agent-0.99.0.tgz
    version: 0.99.0
  - apiVersion: v2
    appVersion: v0.98.4
    created: "2026-09-22T16:59:58.729518105Z"
    description: A Helm chart for hub agent
    digest: 0fc50ee380977d97e0705f4b1f0ceedef0ceedf756c226fc2ecfafc766856b56
    name: hub-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/hub-agent-0.98.4.tgz
    version: 0.98.4
  - apiVersion: v2
    appVersion: v0.98.3
    created: "2026-09-18T20:53:37.063244566Z"
    description: A Helm chart for hub agent
    digest: 7ffb9dec2d6d902cdbaebaebb3a2ce476ef6b09ed83e45f4f552e28ab5938c51
    name: hub-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/hub-agent-0.98.3.tgz
    version: 0.98.3
  - apiVersion: v2
    appVersion: v0.98.2
    created: "2026-09-18T20:20:16.046422769Z"
    description: A Helm chart for hub agent
    digest: 7f0d2a5f27c044996a8789e69fe70a87ffbf7de817d79c7fbadef7e208ec5d21
    name: hub-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/hub-agent-0.98.2.tgz
    version: 0.98.2
  - apiVersion: v2
    appVersion: v0.98.1
    created: "2026-09-18T19:43:25.718973197Z"
    description: A Helm chart for hub agent
    digest: 2a7d3e2da267b2d3fe3feb5188f0a42aa078ecf277e294dcd4c012276a5084a2
    name: hub-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/hub-agent-0.98.1.tgz
    version: 0.98.1
  - apiVersion: v2
    appVersion: v0.98.0
    created: "2026-09-02T20:50:28.731988263Z"
    description: A Helm chart for hub agent
    digest: 24ceccc30cf16f92255b7075eeee8fa9111676d605adda721126b3a4a414c3c0
    name: hub-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/hub-agent-0.98.0.tgz
    version: 0.98.0
  - apiVersion: v2
    appVersion: v0.97.0
    created: "2026-09-18T19:16:34.656421043Z"
    description: A Helm chart for hub agent
    digest: 506a147a17648e9bc1318b6c355843d326f90c440e58c4554b217cb5f3dbe28a
    name: hub-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/hub-agent-0.97.0.tgz
    version: 0.97.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.99.0
    created: "2026-09-02T20:53:37.813105903Z"
    description: Helm chart for member agent.
    digest: 0d1edc52ca0427beeb67756d64302833cf57d572c769010266301f8e0a32a552
    name: member-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/member-agent-0.99.0.tgz
    version: 0.99.0
  - apiVersion: v2
    appVersion: v0.98.4
    created: "2026-09-22T16:59:58.729949035Z"
    description: Helm chart for member agent.
    digest: eb644c63272bfcd9c2e561207d5408eedaff648a4135cecaa83930b3e07d3a37
    name: member-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/member-agent-0.98.4.tgz
    version: 0.98.4
  - apiVersion: v2
    appVersion: v0.98.3
    created: "2026-09-18T20:53:37.063712015Z"
    description: Helm chart for member agent.
    digest: 0890ad67541a5416a828aa2b81283fa2323f774e1425ab2f8586b7c513c6d026
    name: member-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/member-agent-0.98.3.tgz
    version: 0.98.3
  - apiVersion: v2
    appVersion: v0.98.2
    created: "2026-09-18T20:20:16.046858661Z"
    description: Helm chart for member agent.
    digest: 8df95f7a1ed09a6419309a33d6513c86abc255caf8e9885d5e7c79bd20ecb8c3
    name: member-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/member-agent-0.98.2.tgz
    version: 0.98.2
  - apiVersion: v2
    appVersion: v0.98.1
    created: "2026-09-18T19:43:25.719569726Z"
    description: Helm chart for member agent.
    digest: 064ac603af50b4c8f8e6fc4c80368842848127f53c16d6a45065886270f1bed0
    name: member-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/member-agent-0.98.1.tgz
    version: 0.98.1
  - apiVersion: v2
    appVersion: v0.98.0
    created: "2026-09-02T20:50:28.732561046Z"
    description: Helm chart for member agent.
    digest: 526cd7720cec8bcee7469ff570557fdbf1e62119bf7e5eeec3adfdf711d793e0
    name: member-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/member-agent-0.98.0.tgz
    version: 0.98.0
  - apiVersion: v2
    appVersion: v0.97.0
    created: "2026-09-18T19:16:34.657027358Z"
    description: Helm chart for member agent.
    digest: f498ea7fe690b1edac7e2b3c7c3e003a464f9da60b7134455784c1ddda94fa69
    name: member-agent
    type: application
    urls:
    - https://ytimocin.github.io/kubefleet/charts/member-agent-0.97.0.tgz
    version: 0.97.0
generated: "2026-09-22T16:59:58.724385641Z"
